### PR TITLE
Adding go.mod

### PR DESCRIPTION
**Pull request by kenshaw**
Adds go.mod, for go module support.

### CODE REVIEW

**Comment by hekmon** [comment]
Could you restore the dep files ? I think I'm going to support go modules and dep for now.

**Comment by kenshaw** [comment]
Hi -- thanks for all your work. I instead decided to just implement from the ground up a proper/idiomatic Go client library, which works properly and has no external dependencies: https://github.com/kenshaw/transrpc

I also have an almost finished command line utility that is significantly better than `transmission-remote`.

For what it's worth, you should definitely move over to Go modules. `dep` is a solid piece of software, for sure, but the Go community at large has moved on. Again, appreciate the work you did on your original client implementation -- it helped me get a specific project off the ground!

**Comment by hekmon** [comment]
I'm glad it did, I will take a look at your project when I can :)

**Comment by hekmon** [comment]
Finally had time to look into go modules, the module line needed a little fix, cunits now officially supports go modules:
https://github.com/hekmon/cunits/commit/f6dc4dca9104d5f999b81d912d02030d684ca149 
https://github.com/hekmon/cunits/tree/v2.0.2

**Pull request closed without merging**
